elaweb/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, include, url
from supervisorio.views import hello, error404, statistics
from supervisorio.views import monitorar, get_pname, spo2, fr, fc
from supervisorio.views import fa, vt, allparams, add_patient
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'elaweb.views.home', name='home'),
    # url(r'^elaweb/', include('elaweb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/$', include(admin.site.urls)),
    url(r'^$', login_required(hello)),
    url(r'^monitorar/$', login_required(monitorar)),
    url(r'^monitorar/(.*)/$', TemplateView.as_view(template_name='supervisorio/error.html'),
        {'mensagem' : ' Você precisa informar os dados do paciente' }),
    url(r'^api/get_pname/', login_required(get_pname), name='get_pname'),
    url(r'^monitorar/spo2/(.*):(.*):(.*)-(.*)', login_required(spo2)),
    url(r'^monitorar/fr/(.*):(.*)', login_required(fr)),
    url(r'^monitorar/fc/(.*):(.*)', login_required(fc)),
    url(r'^monitorar/fa/(.*):(.*)', login_required(fa)),
    url(r'^monitorar/vt/(.*):(.*)', login_required(vt)),
    url(r'^monitorar/all/(.*):(.*)', login_required(allparams)),
    url(r'^statistics/$', login_required(statistics)),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'supervisorio/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'paciente/add/$', add_patient),
    url(r'^(.*)', login_required(error404)),
    #That's for specific URLs to the supervisorio app
    #url(r'^supervisorio/', include('supervisorio.urls')),
)

supervisorio/urls.py
from django.conf.urls import *
#from supervisorio.models import 

#urlpatterns = patterns('',
#
#)

supervisorio/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.validators import RegexValidator, MinLengthValidator
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db.models.signals import post_save
from django.db.models.signals import pre_delete
import datetime


# Create your models here.
class Aparelho(models.Model):
    idAparelho = models.AutoField(primary_key=True, verbose_name="Número de identificação")
    dataLigacao = models.DateTimeField(auto_now_add=True, verbose_name="Quando foi ligado")
    modeloAparelho = models.CharField(max_length=20, verbose_name="Modelo",
                                      validators=[RegexValidator(regex='^[0-9 ]*[a-zA-Z ][a-zA-Z0-9 ]*$',
                                      message='O nome precisa conter ao menos uma letra, e sem espaços ou caracteres especiais.',
                                      code='nomatch'),
                                      MinLengthValidator(5)],)
    ativo = models.BooleanField(editable=False, default=False)
    nomeAparelho = models.CharField(max_length=20, verbose_name="Nome",
                                    validators=[RegexValidator(regex='^[0-9 ]*[a-zA-Z ][a-zA-Z0-9 ]*$',
                                    message='O nome precisa conter ao menos uma letra, e sem espaços ou caracteres especiais.',
                                    code='nomatch'),
                                    MinLengthValidator(5)],)

    def __unicode__(self):
        if self.ativo == True:
            usado = "Ocupado"
        else:
            usado = "Livre"

        return "%s" % (self.nomeAparelho)

    class Meta:
        app_label = u'Administração'
        db_table = 'supervisorio_aparelho'
        verbose_name = 'Aparelho'
        verbose_name_plural = 'Aparelhos'


class Paciente(models.Model):
    nomePaciente = models.CharField(max_length=40, verbose_name="Nome")
    cpfPaciente = models.CharField(max_length=14, verbose_name="CPF", unique=True,
                                   # Only digits
                                   validators=[RegexValidator(regex=r'^\d{3}\.\d{3}\.\d{3}\-\d{2}$',
                                   message='CPF inválido. Insira apenas números.',
                                   code='nomatch'),
                                   MinLengthValidator(14)],)
    susPaciente = models.CharField(max_length=18, verbose_name="Cartão SUS", unique=True,
                                   # Only digits
                                   validators=[RegexValidator(regex=r'^\d{3}\ \d{4}\ \d{4}\ \d{4}$',
                                   message='Número do cartão SUS inválido. Insira apenas números.',
                                   code='nomatch'),
                                   MinLengthValidator(18)],)
    sexoPaciente = models.CharField(max_length=1, verbose_name="Sexo")
    nomeCuidador = models.CharField(max_length=40, verbose_name="Cuidador")
    telefonePaciente = models.CharField(max_length=14, verbose_name="Telefone",
                                        # Only digits
                                        validators=[RegexValidator(regex=r'^\(\d{2}\)\ \d{4}-\d{4}$',
                                        message='Telefone inválido. Insira apenas números.',
                                        code='nomatch'),
                                        MinLengthValidator(14)],)
    pesoPaciente = models.FloatField(verbose_name="Peso")
    alturaPaciente = models.FloatField(verbose_name="Altura")
    nascimentoPaciente = models.DateField(verbose_name="Nascimento")
    enderecoPaciente = models.TextField(verbose_name="Endereço")
    cidadePaciente = models.CharField(max_length=30, verbose_name="Cidade")
    estadoPaciente = models.CharField(max_length=20, verbose_name="Estado")
    idPaciente = models.AutoField(primary_key=True, verbose_name="Número de identificação")
    cepPaciente = models.CharField(max_length=10, verbose_name="CEP",
                                   # Only digits
                                   validators=[RegexValidator(regex=r'\d{2}\.\d{3}\-\d{3}$',
                                   message='CEP inválido. Insira apenas números.',
                                   code='nomatch'),
                                   MinLengthValidator(10)],)
    aparelhoPaciente = models.ForeignKey('Aparelho', verbose_name="Aparelho", unique=True)

    def __unicode__(self):
        return "%s" % (self.nomePaciente)

    def clean(self):
        if not self.sexoPaciente in 'mfMF':
            raise ValidationError('Gênero não reconhecido.')
        # Modifying the patient
        try:
            try:
                # Modifying to a taken device
                if self.aparelhoPaciente.ativo == True:
                    if self.aparelhoPaciente != Paciente.objects.get(idPaciente=self.idPaciente).aparelhoPaciente:
                        raise ValidationError('Este aparelho já está em uso.')
                        # Updating new device and deactivating previous one
                    else:
                        paciente = Paciente.objects.get(idPaciente=self.idPaciente)
                        aparelho = Aparelho.objects.get(idAparelho=paciente.aparelhoPaciente.idAparelho, ativo=True)
                        self.aparelhoPaciente.ativo = True
                        self.aparelhoPaciente.save()
                        aparelho.ativo = False
                        aparelho.save()
            # Didn't select a device
            except Aparelho.DoesNotExist:
                raise ValidationError('Você precisa selecionar um aparelho.')

        # Adding a new patient
        except Paciente.DoesNotExist:
            try:
                self.aparelhoPaciente.ativo = self.aparelhoPaciente.ativo
                self.aparelhoPaciente.save()
            # Didn't select a device
            except Aparelho.DoesNotExist:
                raise ValidationError('Você precisa selecionar um aparelho.')
        self.aparelhoPaciente.ativo = False
        return self.clean_fields

    class Meta:
        app_label = u'Administração'
        db_table = 'supervisorio_paciente'
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
# It will active a device, as soon as you finish registering
# a patient associated with this device
def ativar_aparelho(sender, instance, **kwargs):
    instance.aparelhoPaciente.ativo = True
    instance.aparelhoPaciente.save()
# Registering the signal for when you register a new patient
post_save.connect(ativar_aparelho, sender=Paciente, dispatch_uid="activate_device2patient")
# It will deactive a device, as soon as you are about
# to delete a patient associated with this device
def desativar_aparelho(sender, instance, **kwargs):
    instance.aparelhoPaciente.ativo = False
    instance.aparelhoPaciente.save()
# Registering the signal for when you delete a patient
pre_delete.connect(desativar_aparelho, sender=Paciente, dispatch_uid="deactivate_device2patient")

# The primary key of this table will be id
# Monitoring consults will be done by idPaciente
# plus growing Id number.
class Monitoramento(models.Model):
    VCestimado = models.FloatField(verbose_name="VC estimado")
    fuga = models.IntegerField(verbose_name="Fuga de ar")
    FRtotal = models.IntegerField(verbose_name="Frequência Respiratória")
    SpO2 = models.IntegerField(verbose_name="Saturação de O2")
    # Remember that timestamp must be part of the compound primary key
    # But for now, Django can't handle composite primary key.
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Data')
    valorCardiaco = models.IntegerField(verbose_name="Pulso Cardíaco")
    idPaciente = models.ForeignKey('Paciente', verbose_name="Paciente")

    def __unicode__(self):
        return "%s (%s)" % (self.timestamp, self.idPaciente.nomePaciente)

    class Meta:
        app_label = u'Administração'
        db_table = 'supervisorio_monitoramento'
        verbose_name = 'Monitoramento'
        verbose_name_plural = 'Monitoramentos'

# alarmes gerados
class Alarmes(models.Model):
    tipoAlarme = models.IntegerField(verbose_name="Tipo de Alarme")
    timestsamp = models.DateTimeField(auto_now_add=False, verbose_name="Hora de disparo")
    idPaciente = models.ForeignKey('Paciente', verbose_name="Paciente")

    def __unicode__(self):
        return "%s (%s) [%s]" % (self.timestamp, tipoAlarme, self.idPaciente.nomePaciente)
    class Meta:
        app_label = u'Administração'
        db_table = 'supervisorio_alarmes'
        verbose_name = 'Alarmes'

templates/supervisorio/all.html
{% extends "supervisorio/base.html" %}

{% block content %}
<center><p> <a class="btn btn-default" href="javascript:history.go(-1)" role="button"> Retornar </a> <a class="btn btn-default" href="/admin/Administra%C3%A7%C3%A3o/paciente/{{ id }}/" role="button"> Visualizar Perfil </a> <a class="btn btn-default" href="javascript:location.reload(true);" role="button"> Atualizar </a> </p>
<script src="{{ STATIC_URL}}js/highcharts.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
$(function () {
        $('#container').highcharts({
            chart: {
                type: 'spline',
                zoomType: 'x'
            },
            title: {
                text: 'Monitoramento de Parâmetros'
            },
            subtitle: {
text: '{{ nomePaciente }}'
            },
            xAxis: {
                type: 'datetime',
                labels: {
                    overflow: 'justify'
                }
            },
            yAxis: {
                labels: {
                    format: '{value}'
                },
                title: {
                    text: 'Todos os parâmetros'
                },
                min: 0,
                minorGridLineWidth: 0,
                gridLineWidth: 0,
                alternateGridColor: null,
            },
            tooltip: {
                formatter : function() {
                                console.log(this);
                                return this.y + ' ' +  this.series.tooltipOptions.valueSuffix;
                            }
            },
            plotOptions: {
                spline: {
                    lineWidth: 4,
                    states: {
                        hover: {
                            lineWidth: 5
                        }
                    },
                    marker: {
                        enabled: false
                    },
                    pointInterval: 1000, // one point per second
                }
            },
            series: [{
                name: 'Saturação de Oxigênio',
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ spo2 }},
                tooltip: {
                    valueSuffix: '% de 760 mmHg'
                }
            }, {
                name: 'Frequência Respiratória',
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ fr }},
                tooltip: {
                    valueSuffix: 'rpm'
                }
            }, {
                name: 'Frequência Cardíaca',
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ fc }},
                tooltip: {
                    valueSuffix: 'bpm'
                }
            }, {
                name: 'Fuga de Ar',
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ fa }},
                tooltip: {
                    valueSuffix: 'L/min'
                }
            }, {
                name: 'Volume Total Estimado',
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ vt }},
                tooltip: {
                    valueSuffix: 'L'
                }
            }]
            ,
            navigation: {
                menuItemStyle: {
                    fontSize: '10px'
                }
            }
        });
    });
</script>
{% endblock %}

templates/supervisorio/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Um Anjo para ELA - Laboratório de Inovação Tecnológica em Saúde LAIS HUOL UFRN</title>
    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.maskedinput.js"></script>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <ul class="nav navbar-nav navbar-collapse collapse">
                  <li><a href="http://lais.huol.ufrn.br" class="navbar-brand" target="_blank">
                  <img alt="Laboratório de Inovação Tecnológica em Saúde" height=25 width=25 src="{{ STATIC_URL }}img/logo.png"></a></li>
                  <a class="navbar-brand" href="/"><b>ELAWeb</b></a>
            </div>

            <ul class="nav navbar-nav navbar-collapse collapse">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Paciente</b><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="menu"><a href="/paciente/add/" class="twitter-share-button"><i class="glyphicon glyphicon-plus"></i> Adicionar um novo</a>
                    <li class="menu"><a href="/admin/Administra%C3%A7%C3%A3o/paciente/" class="twitter-share-button"><i class="glyphicon glyphicon-list"></i> Listar todos os pacientes</a>
                    <li class="menu"><a href="/monitorar/" class="twitter-share-button"><img src="{{ STATIC_URL }}img/chart.png" width=15 height=15></i> Monitorar</a>
                    <li class="menu"><a href="/statistics/" class="twitter-share-button"><i class="glyphicon glyphicon-list-alt"></i> Estatísticas</a>
                </ul>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Ventilador</b><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="menuilators"><a href="/admin/Administra%C3%A7%C3%A3o/aparelho/add/" class="twitter-share-button"><i class="glyphicon glyphicon-plus"></i> Adicionar um novo</a>
                    <li class="menu"><a href="/admin/Administra%C3%A7%C3%A3o/aparelho/" class="twitter-share-button"><i class="glyphicon glyphicon-list"></i> Listar todos os ventiladores</a>
                    <li class="menu"><a href="#" id="solicitar_reparo" class="twitter-share-button"><i class="glyphicon glyphicon-wrench"></i> Solicitar Reparo</a>
                </ul>
                <li class="dropdown"><a href="/admin/"><b>Administração</b></a></li>
                <li class="dropdown"><a href="/logout/"><b>Sair do sistema</b></a></li>
                <li class="dropdown"><a href="/help/"><img src="{{ STATIC_URL }}img/help.png" height=25 width=25><b>Ajuda</b></a></li>
            </ul>
            <div class="navbar-collapse collapse">
                <form class="navbar-form navbar-right" role="form">
                    <a class="btn btn-primary">Você está logado como {{ user.username }}.</a>
                </form>
            </div><!--/.navbar-collapse -->
        </div>
    </div>
<br><br><br><br>
<div id="content" class="container theme-showcase">
    <center><div id="alert-area"></div></center>
    <script>
        function newAlert (type, message) {
            $("#alert-area").append($("<div class='alert-message " + type + " fade in' data-alert><p> " + message + " </p></div>"));
            $(".alert-message").delay(3000).fadeOut("slow", function () { $(this).remove(); });
        }
        $('#solicitar_reparo').click(function(e) {
            e.preventDefault();
            newAlert('success', '<a class="btn btn-danger">Essa função ainda não foi implementada.</a>');
        });
    </script>

{% block content %}{% endblock %}

</div>

<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

</body>
</html>

<div class="container">


    <style> #footer { position:fixed; width:84%; height:100px; } </style>

    <center><footer id="footer">
    <hr>
        <center><p>Um Anjo para ELA - Sistema Supervisório para Monitoramento Homecare de Pacientes com Esclerose Lateral Amiotrófica</p>
    <div class="well well-small">
        <center><p>Copyright 2013 &copy; Laboratório de Inovação Tecnológica em Saúde</p>
        <center><p>LAIS HUOL UFRN</p>
    </div>
    </footer>
</div> <!-- /container -->
    <script>
        x = $('#content').height()+70; // +70 gives space between div and footer
        y = $(window).height();

        if (x+160<=y){ // 160 is the height of your footer
            $('#footer').css('top', y-160+'px');// again 160 is the height of your footer
            $('#footer').css('display', 'block');
        }else{
            $('#footer').css('top', x+'px');
            $('#footer').css('display', 'block');
        }
    </script>

templates/supervisorio/error.html
{% extends "supervisorio/base.html" %}

{% block content %}
<div class="ui-widget">
    <center><a href="javascript:history.go(-1)" class="btn btn-danger"><b><u>Atenção:</b></u>{{ mensagem }}.<br>Clique nesta barra para voltar à página anterior.</a>
</div>
{% endblock %}

templates/supervisorio/fa.html
{% extends "supervisorio/base.html" %}

{% block content %}
<center><p> <a class="btn btn-default" href="javascript:history.go(-1)" role="button"> Retornar </a> <a class="btn btn-default" href="/admin/Administra%C3%A7%C3%A3o/paciente/{{ id }}/" role="button"> Visualizar Perfil </a> <a class="btn btn-default" href="javascript:location.reload(true);" role="button"> Atualizar </a> </p>
<script src="{{ STATIC_URL}}js/highcharts.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
$(function () {
        $('#container').highcharts({
            chart: {
                type: 'spline',
                zoomType: 'x'
            },
            title: {
                text: 'Monitoramento de Parâmetros'
            },
            subtitle: {
text: '{{ nomePaciente }}'
            },
            xAxis: {
                type: 'datetime',
                labels: {
                    overflow: 'justify'
                }
            },
            yAxis: {
                title: {
                    text: 'Fuga de Ar (L/min)'
                },
                min: 0,
                minorGridLineWidth: 0,
                gridLineWidth: 0,
                alternateGridColor: null,
                plotBands: [{ // Perigo
                    from: 61.0,
                    to: 100.0,
                    color: 'rgba(255, 10, 10, 0.7)',
                    label: {
                        text: 'Zona de Perigo',
                        style: {
                            color: '#606060'
                        }
                    }
                }, { // Fora de perigo
                    from: 0.0,
                    to: 60.0,
                    color: 'rgba(255, 255, 255, 0.1)',
                    label: {
                        text: 'Fora de Perigo',
                        style: {
                            color: '#606060'
                        }
                    }
                }]
            },
            tooltip: {
                valueSuffix: ' L/min'
            },
            plotOptions: {
                spline: {
                    lineWidth: 4,
                    states: {
                        hover: {
                            lineWidth: 5
                        }
                    },
                    marker: {
                        enabled: false
                    },
                    pointInterval: 1000, // one point per second
                }
            },
            series: [{
                name: 'Fuga de Ar',
                // below, we will say when the monitoring started
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ fa }}
            }]
            ,
            navigation: {
                menuItemStyle: {
                    fontSize: '10px'
                }
            }
        });
    });
</script>
{% endblock %}

templates/supervisorio/fc.html
{% extends "supervisorio/base.html" %}

{% block content %}
<center><p> <a class="btn btn-default" href="javascript:history.go(-1)" role="button"> Retornar </a> <a class="btn btn-default" href="/admin/Administra%C3%A7%C3%A3o/paciente/{{ id }}/" role="button"> Visualizar Perfil </a> <a class="btn btn-default" href="javascript:location.reload(true);" role="button"> Atualizar </a> </p>
<script src="{{ STATIC_URL}}js/highcharts.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
$(function () {
        $('#container').highcharts({
            chart: {
                type: 'spline',
                zoomType: 'x'
            },
            title: {
                text: 'Monitoramento de Parâmetros'
            },
            subtitle: {
text: '{{ nomePaciente }}'
            },
            xAxis: {
                type: 'datetime',
                labels: {
                    overflow: 'justify'
                }
            },
            yAxis: {
                title: {
                    text: 'Frequência Cardíaca (bpm)'
                },
                min: 0,
                minorGridLineWidth: 0,
                gridLineWidth: 0,
                alternateGridColor: null,
                plotBands: [{ // Perigo
                    from: 0.0,
                    to: 60.0,
                    color: 'rgba(255, 10, 10, 0.7)',
                    label: {
                        text: 'Zona de Perigo',
                        style: {
                            color: '#606060'
                        }
                    }
                }, { // Fora de perigo
                    from: 61.0,
                    to: 100.0,
                    color: 'rgba(255, 255, 255, 0.1)',
                    label: {
                        text: 'Fora de Perigo',
                        style: {
                            color: '#606060'
                        }
                    }
                }, { // Perigo
                    from: 101.0,
                    to: 150.0,
                    color: 'rgba(255, 10, 10, 0.7)',
                    label: {
                        text: 'Zona de Perigo',
                        style: {
                            color: '#606060'
                        }
                    }
                   }]
           },
            tooltip: {
                valueSuffix: ' bpm'
            },
            plotOptions: {
                spline: {
                    lineWidth: 4,
                    states: {
                        hover: {
                            lineWidth: 5
                        }
                    },
                    marker: {
                        enabled: false
                    },
                    pointInterval: 1000, // one point per second
                }
            },
            series: [{
                name: 'Frequência Cardíaca',
                // below, we will say when the monitoring started
                pointStart: Date.UTC(2014, 0, 14, 1, 1, 1),
                data: {{ fc }}
            }]
            ,
            navigation: {
                menuItemStyle: {
                    fontSize: '10px'
                }
            }
        });
    });
</script>
{% endblock %}

templates/supervisorio/patient_add.html
{% extends "supervisorio/base.html" %}
{% block content %}
<div class="row">
{% if user.is_superuser %}


<form action="/paciente/add/" method="post">{% csrf_token %}
{{ form.non_field_errors }}
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}
<br>
<center><input type="submit" class="btn btn-primary" style="height:50px; width:200px" value="Adicionar paciente" />
</form>
</div>

<script>
$(function() {
    $('#id_nascimentoPaciente').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1900:2014',
    });
});
$(function(){
    $('#id_cpfPaciente').mask("999.999.999-99",{placeholder:" "});
    $('#id_susPaciente').mask("999 9999 9999 9999",{placeholder:" "});
    $('#id_telefonePaciente').mask("(99) 9999-9999",{placeholder:" "});
    $('#id_nascimentoPaciente').mask("99/99/9999",{placeholder:" "});
    $('#id_cepPaciente').mask("99.999-999",{placeholder:" "});
});

$('#id_pesoPaciente').keypress(function(event) {
    if (event.which != 37 || event.which != 39) {
        if (event.which < 46 || event.which > 59) {
            event.preventDefault();
        } // prevent if not number/dot
        if (event.which == 46 && $(this).val().indexOf('.') != -1) {
            event.preventDefault();
        } // prevent if already dot
    }
});
$('#id_alturaPaciente').keypress(function(event) {
    if (event.which != 37 || event.which != 39) {
        if (event.which < 46 || event.which > 59) {
            event.preventDefault();
        } // prevent if not number/dot
        if (event.which == 46 && $(this).val().indexOf('.') != -1) {
            event.preventDefault();
        } // prevent if already dot
    }
});

</script>

<style>
form {
    width: 400px;
    padding: 20px;
    border: 1px solid #270644;
}
label {
      width: 25%;
}
</style>

{% else %}
    <center><a href="javascript:history.go(-1)" class="btn btn-danger"><b><u>Atenção:</b></u> Infelizmente, apenas usuários administradores podem adicionar novos pacientes.<br>Clique nesta barra para voltar à página anterior.</a></p>
{% endif %}
{% endblock %}

templates/supervisorio/statistics.html
{% extends "supervisorio/base.html" %}

{% block content %}
<div class="ui-widget">
    <p><p><b>Número de pacientes</b>: {{ numPacientes }}</p>
    <p><b>Número de aparelhos</b>: {{ numAparelhos }}</p>
    <p><b>Número de Amostras</b>: {{ numMonitoramentos }}</p>
    <p><b>Número de usuários</b>: {{ numUsuarios }}</p>
    <p><b>Número de grupos</b>: {{ numGrupos }}</p>
</div>
{% endblock %}